spring:
  application:
    name: service-router
  cloud:
    gateway:
      routes:
      - id: rota_1
        uri: lb://SERVICE-PRIMEIRO
        order: 0
        predicates:
        - Path=/SERVICE-PRIMEIRO/**
        filters:
        - StripPrefix=1
        - AddResponseHeader=X-Response-Default-header, Default-Bar
        
      - id: rota_2
        uri: lb://SERVICE-SEGUNDO
        order: 0
        predicates:
        - Path=/SERVICE-SEGUNDO/**
        filters:
        - StripPrefix=1
        - AddResponseHeader=X-Response-Default-footer, Default-Bar

server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: false
    hostname: localhost
